### ISSUE TITLE
Incorrect output when multiple transition properties are used

### ISSUE THREAD

**Issue by jarektomanek** [nDmitry/grunt-autoprefixer#123]
Source CSS:

``` css
.example {
    transition: filter 1s, transform 2s;
}
```

Output:

``` css
.example {
    transition: -webkit-filter 1s, -webkit-transform 2s, filter 1s, -webkit-transform 2s;
}
```

Issue:
"-webkit-transform 2s" is listed twice, while "transform 2s" is not listed at all.

Config: `browsers: ['last 2 versions']`
grunt-autoprefixer version: 3.0.4
