### ISSUE TITLE
Not working after fresh install

### ISSUE THREAD

**Issue by seniorpreacher** [nDmitry/grunt-autoprefixer#22]
I just installed this plugin via npm.

I added this basic settings to my Gruntfile:

``` coffeescript
    autoprefixer:
        src: '<%= outDir %>/*.css'
```

of course, with the `loadNpmTasks` as well, but when I call `grunt autoprefixer` it doesn't have affect on the files. There are 5 css files in the folder and grunt outputs **`File "src" prefixed.`** 5 times.

I tried to add this short, prefix needed css: 

``` css

#test-rule{
    transform: rotate(90deg);
    user-select: none;
}

```

.. but nothing changed.

**What do I do wrong?**

OS: Win 8.1
nodeJs: 0.10.24
