### ISSUE TITLE
-ms-transform not added and * box-sizing removed

### ISSUE THREAD

**Issue by patrick-wc** [nDmitry/grunt-autoprefixer#34]
Hi

I've just been testing this out from a tutorial I found on CSS-Tricks http://css-tricks.com/autoprefixer/ . I was wondering, I've tried both with and without the option of ie 9 support specified in the autoprefixer: { options, but for me autoprefixr is not outputing -ms-transform as it does in the linked tutorial.

Also, I tried adding a catch all box-sizing: border-box code block:

```
*, *:after, *:before {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}

```

But this gets completely stripped out by autoprefixer...

For -ms-transform I must have messed up something in the options, but in that tutorial even if none are specified it still adds the -ms-transform variable. For box-sizing, are \* selectors not supported?

Thanks

**Comment by sbedulin** [comment]
I have similar problem:
`-ms-transform` is not added with config `last 2 versions, ie >= 9` (or just `ie >= 9`, or `Explorer 9`)

Input:
```css
div {
  display: flex;
  transition: transform 1s;
}
```

Output:
```css
div {
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  transition: -webkit-transform 1s;
  transition: transform 1s;
}
```

I used Autoprefixer Playground for testing http://jsbin.com/gufoko/quiet
![Missing -ms-transform](http://content.screencast.com/users/sbedulin/folders/Jing/media/96568f1a-bc33-4287-aa4e-8c8ceec9c851/2015-02-27_1612.png)
