### ISSUE TITLE
Comments get filtered out

### ISSUE THREAD

**Issue by fragje** [nDmitry/grunt-autoprefixer#38]
I'm using grunt-autoprefixer with  [kss-node](https://github.com/hughsk/kss-node), and are using some specific comment syntax to make it work. When I use kss-node class `{$modifiers}` grunt-autoprefixer filters this out. Tested [autoprefixer sublime plugin](https://github.com/sindresorhus/sublime-autoprefixer), but did not have any problem then.

Css before autoprefixer:

``` css
/*
Buttons

Markup:
<a href="#0" class="{$modifiers}">Link Button</a>
<button class="{$modifiers}">Button Element</button>
<input type="button" class="btn {$modifiers}" value="Input Element"/>

.btn               - Default button style
.btn-cta           - Call to action buttons
.btn-neutral       - Neutral button
.btn-text          - Link button

Styleguide 1.6.1
*/
/* line 17, ../../../_sass/partials/atoms/_buttons.scss */
.btn, .btn-cta, .btn-neutral, .btn-text {
  color: white;
  background-color: dodgerblue;
  display: inline-block;

```

Css after grunt-autoprefixer:

``` css
/* line 17, ../../../_sass/partials/atoms/_buttons.scss */

.btn,
.btn-cta,
.btn-neutral,
.btn-text {
  color: white;
  background-color: dodgerblue;
  display: inline-block;
```
