### ISSUE TITLE
Warning: unknown word because of sass commenting

### ISSUE THREAD

**Issue by srekoble** [nDmitry/grunt-autoprefixer#84]
I struggled out to figure out why I was getting this warning:

`Warning: assets/sass/main.scss:306:29: Unknown word Use --force to continue.`

Then after a long debugging process I realise that the problem was the comment format that we use for several cases. Check the following example:

``` SCSS
.box {
    position: relative;

    &:before {
      content: "\e812"; // star icon
      color: red;
      font-size: 13px;
    }
 }
```

The sass comment next to property `content: "\e812";` seemed to block the grunt task

The same problem would also happen in a comment syntax like the following.

``` SCSS
.box { // Some box usage
    position: relative;

    &:before {
      content: "\e812";
      color: red;
      font-size: 13px;
    }
 }
```

Then if I just implement a sass comment in a new line like the following example the problem doesn't exist.

``` SCSS

 // Some box usage

.box {
    position: relative;

    &:before {
      content: "\e812";
      color: red;
      font-size: 13px;
    }
 }
```

I believe that this a common problem that needs to be fixed, I would be happy to provide any informations that can be useful.
