### ISSUE TITLE
Autoprefixer is removing 'display: -webkit-box'

### ISSUE THREAD

**Issue by stephencarr** [nDmitry/grunt-autoprefixer#89]
My config:

```javascript
autoprefixer: {
            options: {
                browsers: ['> 1%', 'ie >= 7'],
                diff: true
            },
            single_file: {
                src: './source.css'
            }
        }
```

My source CSS

```css
div {
        display: block;
        display: -webkit-box;
        line-height: 1.2;
        text-overflow: ellipsis;
        height: 12px; 
        -webkit-line-clamp: 3;
        -webkit-box-orient: vertical;
      }
```

When autoprefixer parses this it sweeps out 'display: -webkit-box;'. Playing with the interactive tool (http://jsbin.com/gufoko/quiet) this does not happen. Where am I going wrong?

**Comment by ai** [comment]
What is input CSS?

In you output example prefixed `display: -webkit-box` has no unprefixed `display: flex`. If Autoprefixer finds prefix without unprefixed version, it decide that is browser-specific hack and didn’t remove outdated prefix (because it is look like that you want to hack some bug in old version like `-webkit-transform: translate3d(0, 0, 0)`).

**Comment by stephencarr** [comment]
I am trying to implement multiple line text truncation:
http://css-tricks.com/line-clampin/

I understand this is a bit of a hack, but just wondered why the interactive tool works but my local grunt job does not.

**Comment by ai** [comment]
Show me input CSS :).

But online demo doesn’t remove this kind of hacks too.

**Comment by stephencarr** [comment]
Input CSS:

```css
div {
        display: block;
        display: -webkit-box;
        line-height: 1.2;
        text-overflow: ellipsis;
        height: 12px; 
        -webkit-line-clamp: 3;
        -webkit-box-orient: vertical;
      }
```
